need opengl path because of precompiled glew header
In file included from precompiled.h:89:0:
../libs/glew/include/GL/glew.h:1188:24: fatal error: GL/glu.h: No such file or d
irectory
 #    include <GL/glu.h>
                        ^